### ISSUE TITLE
repeatedly showing when it clearly states it wont

### ISSUE THREAD

**Issue by LisaBurney** [browser-update/browser-update#399] opened 2018-06-12 18:27 UTC
I know my browser is out of date. This little tiny peice of crap laptop I use does not have enough space to download ANY updates, and I have nothing stored on it at all. It gets very annoying with your stupid thing popping up telling me to update when I cannot. I have told it to stop several hundred times now. It has repeatedly told me it will not pop up anymore, but yet it does. I do my schoolwork on this computer only, and this stupid thing keeps blocking access to important tabs. I am forced to click to ignore it over and over again just for it to open up a new browser page and then as soon as I go back to the one I was on it pops up again. once again blocking what I need to click. MAKE IT GO AWAY!!! I can't stand it and it makes me angry!

**Comment by josselex** [comment] 2018-06-13 06:46
I'm sorry for that. We will try to fix this as soon as possible. This is
not the expected behaviour.
In order to find the error can you tell me what you see on this site:
http://browser-update.org/test.html

Could you also tell me on which site you get the out-of-date message
repeatedly?

And are cookies in your browser turned on?

Am Di., 12. Juni 2018 um 20:27 Uhr schrieb LisaBurney <
notifications@github.com>:

**Comment by LisaBurney** [comment] 2018-06-17 12:20
Just got the email.
Okay, so on that website at the top of the page pops up that web browser
out of date message gining me two options of updating or ignoring. Just
like on flvs.net right after I sign in to my account. Click ignore it
changes to never see again and that time it actually disappeared before I
could click anything, and i dont see it anymore, which is fine.
Not sure if you want me to tell you everything on the page, but here goes:
Identification
User-agent-string (http header):
Mozilla/5.0 (windows nt 10.0; wow64) applewebkit/537.36 (khtml, like gecko)
chrome/58.0.2988.0 safari/537.36

User-agent-string (javascript):
Mozilla/5.0 (windows nt 10.0; wow64) applewebkit/537.36 (khtml, like gecko)
chrome/ 58.0.2988.0 safari/537.36

Detection
Detected browser as (javascript):
Chrome 58

Browser (header):
Chrome 58

System (header):
Windows 10

Language
Language ( http header):
En-us, en;q=0.8

Lang (javascript):
En

More
{"ip": "127.0.0.1", "country": "us", "ip3": "162.158.78.28", "cont": "na"}


I also see an advertisement to download brave.

Also when i am on my school page and click on the ignore then never show
again it pops up into a new tab. On this page it says:
You will no longer see warnings about your outdated browsers on this site.
And then it warns me that my site may not work properly.
Then it also gives the option to change my mind and update anyway.
When i go back to the school page its not there for like 30 seconds and
then that bar pops back up across the top of my page again.

**Comment by josselex** [comment] 2018-07-26 10:17
I now found the bug. The problem was on some sites with a certain configuration of browser-update.
Can you check if it is fixed now?
Maybe you need to press shift+reload on the site in order that the changes take affect.

**Closed** 2018-07-26 10:17 UTC
