### ISSUE TITLE
Problem with this.op when using with webpack

### ISSUE THREAD

**Issue by husky-g** [browser-update/browser-update#351] opened 2017-05-06 15:48 UTC
Hi, we have a problem with the module. It does not work and it seems that the problem is in the line
 window._buorgres=this.op=op||{};
'this' is undefined and in browser console there is an error: Cannot set property 'op' of undefined. Can it be fixed?

We use the latest version of browser-update and the latest version of webpack. If you can not reproduce this behaviour we can provide a piece of code that cause the problem.

**Comment by josselex** [comment] 2017-05-09 09:25
Hi!
I found an error in this line when not passing options to the function. This is fixed in 829d5f3b2111932a55beaa92ae288ffa03c23dda

But I cannot reproduce your problem with this not being defined.
Could you give me a piece of code to reproduce this?

**Comment by josselex** [comment] 2017-05-15 07:33
Hi @husky-g !
Does the Problem still persist? Can you give me a piece of code to reproduce?

**Comment by mren** [comment] 2017-05-22 15:10
Hello @josselex,

i made some reproducaable gist for you: https://gist.github.com/mren/afb30cc4b381da4158db1834a43689b7

**Comment by josselex** [comment] 2017-05-23 07:27
Hi @mren,

I think you for got the index file!

Thomas

2017-05-22 17:10 GMT+02:00 mren <notifications@github.com>:

**Comment by mren** [comment] 2017-05-23 10:34
Uh yes, thanks!

I added `index.js` to the gist. https://gist.github.com/mren/afb30cc4b381da4158db1834a43689b7

Sorry!

**Closed** 2017-05-23 13:07 UTC
